name: Checks

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "UNIQ_ID=$(date +'%y%m%d')-${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
